baseURL = "https://andimatteo.github.io/"
languageCode = "en-us"
title = "Andrea Di Matteo"
theme = ["hugo-admonitions","anubis2"]   # ORDINE: prima il componente

[params]
description = "Computer Engineering Student at Scuola Superiore Sant'Anna"
enableSocial = true           # Enables social icons
enableThemeSwitcher = true    # Light/Dark toggle
enableMathGlobally = false    # Enable MathJax globally if needed

[params.Author]
    name = "Andrea Di Matteo"

[[params.social]]
id = "github"
url = "https://github.com/andimatteo"


[[params.social]]
id = "email"
url = "mailto:andrea.dimatteo@santannapisa.it"

[[params.social]]
id = "linkedin"
url = "https://linkedin.com/in/adimatteo"


[markup]
  [markup.highlight]
    style = "onedark"
    lineNos = true         # Enable line numbers (optional)

[menu]

    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Tags"
        url = "/tags/"
        weight = 3

    [[menu.main]]
        name = "Archive"
        url = "/posts/"
        weight = 4



[caches]
  [caches.images]
    dir = ':cacheDir/images'



[params.hugoAdmonitions]
  enable = true
